# embed.ps1 - convert a binary file into a C++ byte-array header
#
# Usage (normally invoked by build.bat):
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\embed.ps1
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\embed.ps1 -Source index.html
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\embed.ps1 -Source favicon.ico -Output src\app_ico.h -Symbol APP_ICON
#
# Defaults: index.html -> src\index_html.h with symbol INDEX_HTML
param(
    # 注意：这里刻意不用 $Input 作参数名。$Input 是 PowerShell 的自动变量（承载管道
    # 输入），一旦脚本出现在管道里就会被覆盖，传进来的值会被静默忽略。
    # 保留 -Input 作为别名只是为了调用方便。
    [Alias("Input")]
    [string]$Source = "",
    [string]$Output = "",
    # 生成的 C++ 数组符号名；长度常量命名为 <Symbol>_LEN
    [string]$Symbol = "INDEX_HTML"
)

$ErrorActionPreference = "Stop"

$toolDir = $PSScriptRoot
$rootDir = (Resolve-Path (Join-Path $toolDir "..")).Path

if ([string]::IsNullOrWhiteSpace($Source)) {
    $Source = Join-Path $rootDir "index.html"
}
if ([string]::IsNullOrWhiteSpace($Output)) {
    $Output = Join-Path $rootDir "src\index_html.h"
}

$inPath = (Resolve-Path $Source).Path
$outPath = [System.IO.Path]::GetFullPath($Output)

$bytes = [System.IO.File]::ReadAllBytes($inPath)
if ($bytes.Length -eq 0) { throw "source file is empty: $inPath" }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("// Auto-generated by tools/embed.ps1 - do not edit.")
[void]$sb.AppendLine("// source: $([IO.Path]::GetFileName($inPath)) ($($bytes.Length) bytes)")
[void]$sb.AppendLine("static const unsigned char $Symbol[] = {")

$perLine = 20
for ($i = 0; $i -lt $bytes.Length; $i++) {
    if ($i % $perLine -eq 0) { [void]$sb.Append("    ") }
    [void]$sb.Append($bytes[$i])
    if ($i -lt $bytes.Length - 1) { [void]$sb.Append(",") }
    if ($i % $perLine -eq ($perLine - 1)) { [void]$sb.AppendLine() }
}
[void]$sb.AppendLine()
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const unsigned long long ${Symbol}_LEN = $($bytes.Length);")

[System.IO.File]::WriteAllText($outPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "  [embed] $inPath -> $outPath ($($bytes.Length) bytes)"
