# embed.ps1 - convert index.html into a C++ byte-array header (index_html.h)
#
# Usage (normally invoked by build.bat):
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\embed.ps1
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\embed.ps1 -Input index.html
param(
    [string]$Input  = "",
    [string]$Output = ""
)

$ErrorActionPreference = "Stop"

$toolDir = $PSScriptRoot
$rootDir = (Resolve-Path (Join-Path $toolDir "..")).Path

if ([string]::IsNullOrWhiteSpace($Input)) {
    $Input = Join-Path $rootDir "index.html"
}
if ([string]::IsNullOrWhiteSpace($Output)) {
    $Output = Join-Path $rootDir "src\index_html.h"
}

$inPath = (Resolve-Path $Input).Path
$outPath = [System.IO.Path]::GetFullPath($Output)

$bytes = [System.IO.File]::ReadAllBytes($inPath)
if ($bytes.Length -eq 0) { throw "index.html is empty: $inPath" }

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("// Auto-generated by tools/embed.ps1 - do not edit.")
[void]$sb.AppendLine("// source: index.html ($($bytes.Length) bytes)")
[void]$sb.AppendLine("static const unsigned char INDEX_HTML[] = {")

$perLine = 20
for ($i = 0; $i -lt $bytes.Length; $i++) {
    if ($i % $perLine -eq 0) { [void]$sb.Append("    ") }
    [void]$sb.Append($bytes[$i])
    if ($i -lt $bytes.Length - 1) { [void]$sb.Append(",") }
    if ($i % $perLine -eq ($perLine - 1)) { [void]$sb.AppendLine() }
}
[void]$sb.AppendLine()
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("static const unsigned long long INDEX_HTML_LEN = $($bytes.Length);")

[System.IO.File]::WriteAllText($outPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "  [embed] $inPath -> $outPath ($($bytes.Length) bytes)"
